# Site settings
title: "Chase McCoy"
email: desk@chasemccoy.net
description: > # this means to ignore newlines until "baseurl:"
  Hello. Welcome to the weblog of Sean Sperte. This is a collection of notes related to design, technology, and faith.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chasemccoy.github.io" # the base hostname & protocol for your site
twitter_username: chase_mccoy
github_username: chasemccoy

collections:
  galleries:
    output: true
    permalink: /:collection/:title/index.html

# Build settings
permalink: /:title
paginate: 10
paginate_path: "/:num"
markdown: kramdown

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "galleries"
    values:
      layout: "gallery"