---
title: Cosmic Owl Studio
timezone: UTC
collections:
  design:
    title: Design
    output: true
    permalink: "/:collection/:title/index.html"
  photos:
    title: Photos
    output: true
    permalink: "/:collection/:title/index.html"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: photos
  values:
    layout: gallery
- scope:
    path: ''
    type: design
  values:
    layout: gallery
email: desk@chasemccoy.net
description: 'Hello. Welcome to the weblog of Sean Sperte. This is a collection of
  notes related to design, technology, and faith.

'
baseurl: ''
url: http://chasemccoy.github.io
twitter_username: chase_mccoy
github_username: chasemccoy
permalink: "/:categories/:title"
paginate: 10
paginate_path: "/:num"
markdown: kramdown
