# Site settings
title: "Chase McCoy"
email: desk@chasemccoy.net
description: > # this means to ignore newlines until "baseurl:"
  Hello. Welcome to the weblog of Sean Sperte. This is a collection of notes related to design, technology, and faith.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://seansperte.com" # the base hostname & protocol for your site
twitter_username: chase_mccoy
github_username: chasemccoy

# Build settings
permalink: /entry/:title
paginate: 10
paginate_path: "/:num"
markdown: kramdown

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"